test_catkin_virtualenv/package.xml, test_catkin_virtualenv_py3/package.xml
As per subject.
I would really have expected this to be more of a problem, but I didn't really get any complaints from `catkin`.
=> Remove stray 's' from test package manifests.

catkin_virtualenv/cmake/catkin_generate_virtualenv.cmake, catkin_virtualenv/cmake/combine_requirements.py, catkin_virtualenv/cmake/python3_requirements.txt, test_catkin_virtualenv_py3/requirements.txt
FYI @locusrobotics/robot-software-team 
* Create a base python3_requirements.txt for all python3 packages
* Provide more details during a requirements merge failure
=> Python 3 compatiblity tweaks

catkin_virtualenv/cmake/build_venv.py, catkin_virtualenv/src/dh_virtualenv/deployment.py
Lock down pip version at 9.0.3
=> Fix issues due to pip 10 release

README.md, catkin_virtualenv/cmake/build_venv.py, catkin_virtualenv/cmake/catkin_generate_virtualenv.cmake
FYI @knorth55, supercedes https://github.com/locusrobotics/catkin_virtualenv/pull/23
- Disable py3 builds to get tests to pass
- Move cmake escape processing to a common place
There's some meta-escaping going on here (`\\\'`) that I do _not_ fully understand, but it seems to work better than anything I can come up with for the cmake->make->argparse chain.
=> Clean up extra_pip_args PR

catkin_virtualenv/src/dh_virtualenv/deployment.py
Passing arguments to internal `venv` module was broken, causing defaults to be used at all times.
=> Pass arguments to internal venv module

catkin_virtualenv/scripts/glob_requirements
In principle, an exec_depends package shouldn't be there at build time, so inheriting requirements from it makes no sense.
In practice, inheriting requirements via exec_depends breaks cases where launch and runtime components of packages interfere.
=> Don't inherit requirements from exec_depends

catkin_virtualenv/cmake/common_requirements.txt
catkin-pkg is still available, let's use that instead.
Short of chasing this upstream, I feel that somebody decided `-modules` packages are a construct invented to support debs and doesn't belong on pypi.
=> catkin-pkg-modules has disappeared off pypi

catkin_virtualenv/scripts/build_venv, catkin_virtualenv/src/dh_virtualenv/deployment.py
Test build here http://tailor.locusbots.io/blue/organizations/jenkins/ci%2Ftailor-distro/detail/0.1.16/120/pipeline
Newly released setuptools (45) explicitly not compatible with python2, so we need to make sure we install an older one in py2 venvs.
=> First python2 issue of 2020

catkin_virtualenv/cmake/catkin_generate_virtualenv.cmake
Turns out Cmake's internal 'copy_directory' mechanism botches symlinks. This was interfering with our deb artifacts. I'm merging this with extreme prejudice to make sure the nightly builds are stable tomorrow (today's debs are botched and I don't want anyone installing them), but please still review and we can hash it out tomorrow!
FYI @ayrton04 this is what you were seeing on your machine.
=> Preserve symlinks during copy

catkin_virtualenv/cmake/catkin_generate_virtualenv.cmake
Only warn about INPUT_REQUIREMENTS if a package exports requirements to begin with. Otherwise packages that don't export requirements.in/txt (but consume upstream ones) will be warned about.
=> Fix input requirements warning

README.md, catkin_virtualenv/CMakeLists.txt, catkin_virtualenv/cmake/catkin_generate_virtualenv.cmake, catkin_virtualenv/package.xml, catkin_virtualenv/scripts/collect_requirements, catkin_virtualenv/scripts/venv_check, catkin_virtualenv/scripts/venv_init, catkin_virtualenv/scripts/venv_install, catkin_virtualenv/scripts/venv_lock, catkin_virtualenv/scripts/venv_relocate, catkin_virtualenv/src/catkin_virtualenv/__init__.py, catkin_virtualenv/src/catkin_virtualenv/collect_requirements.py, catkin_virtualenv/src/catkin_virtualenv/relocate.py, catkin_virtualenv/src/catkin_virtualenv/venv.py
From discussion with @abencz, we probably don't want to blindly recommend INPUT_REQUIREMENTS, and instead just ensure that requirements are actually locked.
This actually satisfies the spirit of the RST-3172 better, since we can detect any insufficiently locked requirements.
Sneaks in a python3 port of catkin_virtualenv proper.
- test is defined https://github.com/locusrobotics/catkin_virtualenv/pull/62/files#diff-a043275b2d398f3545b4e19805ea7cbaR144
- test 'main' script and xunit output https://github.com/locusrobotics/catkin_virtualenv/pull/62/files#diff-2c3f93cafacb2e82d2c8b0733c97fb29R31
- test logic https://github.com/locusrobotics/catkin_virtualenv/pull/62/files#diff-df9eea60531facde7a05b91c71e12841R96
=> RST-3172 Check that requirements file is locked

catkin_virtualenv/src/catkin_virtualenv/venv.py
Fix regex to match only files ending in ".py[co]" and not files ending
in "py[co]".
=> Make regex for Python bytecode more selective

README.md, catkin_virtualenv/cmake/catkin_generate_virtualenv.cmake, test_catkin_virtualenv/CMakeLists.txt
=> Don't require catkin_package to be called before catkin_generate_virtualenv

catkin_virtualenv/src/catkin_virtualenv/venv.py
The old version specification would also evaluate to true if `USE_SYSTEM_PACKAGES` was `TRUE` and the base OS already had a version of `setuptools` installed (which is often the case).
On Xenial fi this leads to `20.7.0` satisfying the `<45` requirement, but that version doesn't appear to be compatible with `pip==20.1`.
For context, see #70.
=> Python2: always require a 44.x version of setuptools

catkin_virtualenv/requirements.in, catkin_virtualenv/requirements.txt
This PR fix `rospkg` version above `1.3.0`.
`rosdep>=0.20.1` requires `rospkg>=1.3.0`.
Therefore, I bump the version to `rospkg>=1.3.0`.
Related:
https://github.com/ros-infrastructure/rosdep/issues/807
=> bump rospkg>=1.3.0 for rosdep>=0.20.1

README.md, catkin_virtualenv/cmake/catkin_generate_virtualenv.cmake
Specifically when `catkin_virtualenv` was used in multiple packages.
---
This should allow people who may use some non-isolated builds (such as `catkin_make` or CLion) to be able to use `catkin_virtualenv` without it grinding to a halt.
I did not adjust the documentation about the name change for the build target in the case of a non-isolated build, since the non-isolated build use case does not seem to be _officially_ supported and I did not want to give the idea that it was. I can adjust the README if desired.
=> Make CMake work in non-isolated builds.

catkin_virtualenv/cmake/catkin_generate_virtualenv.cmake
Now `CMAKE_SOURCE_DIR` is used for `requirements.in/txt` path.
This works fine with `catkin build`, but does not work with `catkin_make`.
This is because `catkin_make` uses `catkin_ws/src` as `CMAKE_SOURCE_DIR`.
I change to use `PROJECT_SOURCE_DIR` to avoid this build error.
The build error with `catkin_make` is as follow:
```
make[2]: *** No rule to make target '/tmp/catkin_ws/src/requirements.in', needed by '/tmp/catkin_ws/src/coral_usb_ros/requirements.txt'
```
=> use PROJECT_SOURCE_DIR for requirements in venv_lock

catkin_virtualenv/cmake/catkin_generate_virtualenv.cmake
At current, if I do a catkin build with `CATKIN_ENABLE_TESTING=FALSE`, I get the following error when calling `catkin_generate_virtualenv`.
```
Unknown CMake command "catkin_run_tests_target"
```
This is because it is not defined when `CATKIN_ENABLE_TESTING=FALSE`.
=> Run catkin_run_tests_target only when CATKIN_ENABLE_TESTING is enabled

catkin_virtualenv/cmake/templates/program.devel.in, catkin_virtualenv/cmake/templates/program.install.in, catkin_virtualenv/requirements.in, catkin_virtualenv/requirements.txt
~https://github.com/locusrobotics/catkin_virtualenv/pull/51 works fine, but changing the process name seems to bork something about how the virtualenv is loaded (see test results).~
Replaced bash exec with python magic, this makes python process names very similar to native processes for monitoring purposes.
=> Rename process to program name

catkin_virtualenv/src/catkin_virtualenv/__init__.py
The config file for logging is assumed either `.conf` file or `.yaml` file (i.e. `/opt/ros/noetic/etc/ros/python_logging.conf`) in ROS ecosystem, but currently only `.yaml` file is supported in this package.
This PR changes the `configure_logging` function defined in `__init__.py` to use the existing function to configure logging feature not to differentiate the behavior of loading logging config files.
https://github.com/ros/ros_comm/blob/noetic-devel/tools/rosgraph/src/rosgraph/roslogging.py#L167
=> Use upstream function to configure logging

catkin_virtualenv/package.xml, catkin_virtualenv/setup.py
Recently users of newer distributions who build Noetic from source noticed issues when importing setup from distutils.core.
This problem was discussed on [Discourse](https://discourse.ros.org/t/ros-1-and-python-3-10s-deprecation-of-distutils-core/29834), and we hope that we can make the needed updates to Noetic to allow for future builds from source of Noetic.
As a first step, this PR introduces changes from the [Noetic Migration Guide](https://wiki.ros.org/noetic/Migration#Setuptools_instead_of_Distutils) that addresses the change to the setuptools module instead of distutils.core and the corresponding buildtool_depend tags for python 2&3.
=> Import setup from setuptools instead of distutils.core

catkin_virtualenv/src/catkin_virtualenv/venv.py
This should avoid false positives for the locked venv check
=> Ignore order in requirements consistency check

catkin_virtualenv/src/catkin_virtualenv/venv.py
The `version` variable set here is not used (anymore?).
The `run_command()` failed for me in Ubuntu 22.04 because there is no executable named `python`, only `python3` (without package `python-is-python3` installed).
=> Remove old unused version check that depends on a binary named python

Jenkinsfile, catkin_virtualenv/src/catkin_virtualenv/venv.py
The following is a test to see if clearing the pip cache prevents the weird situation where pip cannot install a package based on requirements.txt. There are instances when a package on the build farm will fail due to venv not being able to pip install the package, even though it exists in pypi. 
In #1 discusses about how pip will often use locally built cached wheels first and how by default pip will use local caching first. Perhaps this could be where there is an issue. 
[1] https://pip.pypa.io/en/stable/topics/caching/
=> Testing with pip cache purge prior to install pip packages

catkin_virtualenv/cmake/templates/program.devel.in, catkin_virtualenv/cmake/templates/program.install.in
While testing https://github.com/locusrobotics/locus_common/pull/289, I noticed that in telegraf all caktin_virtualenv-related processes are being renamed to `/opt/locusrobot`, the truncated program path. The full path was fine for ELK stack and friends, but in the new metrics world we should use the program basename.
A note that https://pypi.org/project/setproctitle/ is different than BSD's setproctitle, in that it calls prctl under the hood, and somehow clobbers cmdline as well.
=> RST-12669 Use program basename instead of full path

catkin_virtualenv/src/catkin_virtualenv/venv.py
This PR modifies the script to locate and execute `pip-compile` from the global path if it is not found within the current virtual environment.
Currently, the script assumes that `pip-compile` is installed within the activated virtual environment.  However, users may have `pip-compile` installed globally and installer does not install the `pip-tools` to the venv space in the case [1].
This change allows the script to search for `pip-compile in the system's PATH if it's not found in the virtual environment's bin directory.
[1] Such users will see the error:
```
Traceback (most recent call last):
File "/home/furushchev/catkin_ws/devel/lib/catkin_virtualenv/venv_lock", line 15, in <module>
exec(compile(fh.read(), python_script, 'exec'), context)
File …
```
=> Find pip-compile in global path if it does not exist in venv
